/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  EnergyMixResponse,
  EnergyUsageWindowModel,
  GetOptimalWindowParams
} from '../generated.schemas';





export const getOptimalWindow = (
    params: GetOptimalWindowParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<EnergyUsageWindowModel>> => {
    
    
    return axios.get(
      `http://localhost:8080/api/optimal-window`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetOptimalWindowQueryKey = (params?: GetOptimalWindowParams,) => {
    return [
    `http://localhost:8080/api/optimal-window`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetOptimalWindowQueryOptions = <TData = Awaited<ReturnType<typeof getOptimalWindow>>, TError = AxiosError<unknown>>(params: GetOptimalWindowParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOptimalWindow>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOptimalWindowQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOptimalWindow>>> = ({ signal }) => getOptimalWindow(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOptimalWindow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOptimalWindowQueryResult = NonNullable<Awaited<ReturnType<typeof getOptimalWindow>>>
export type GetOptimalWindowQueryError = AxiosError<unknown>


export function useGetOptimalWindow<TData = Awaited<ReturnType<typeof getOptimalWindow>>, TError = AxiosError<unknown>>(
 params: GetOptimalWindowParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOptimalWindow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOptimalWindow>>,
          TError,
          Awaited<ReturnType<typeof getOptimalWindow>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOptimalWindow<TData = Awaited<ReturnType<typeof getOptimalWindow>>, TError = AxiosError<unknown>>(
 params: GetOptimalWindowParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOptimalWindow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOptimalWindow>>,
          TError,
          Awaited<ReturnType<typeof getOptimalWindow>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOptimalWindow<TData = Awaited<ReturnType<typeof getOptimalWindow>>, TError = AxiosError<unknown>>(
 params: GetOptimalWindowParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOptimalWindow>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetOptimalWindow<TData = Awaited<ReturnType<typeof getOptimalWindow>>, TError = AxiosError<unknown>>(
 params: GetOptimalWindowParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOptimalWindow>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOptimalWindowQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getEnergyMix = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<EnergyMixResponse>> => {
    
    
    return axios.get(
      `http://localhost:8080/api/energy-mix`,options
    );
  }




export const getGetEnergyMixQueryKey = () => {
    return [
    `http://localhost:8080/api/energy-mix`
    ] as const;
    }

    
export const getGetEnergyMixQueryOptions = <TData = Awaited<ReturnType<typeof getEnergyMix>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEnergyMix>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEnergyMixQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEnergyMix>>> = ({ signal }) => getEnergyMix({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEnergyMix>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEnergyMixQueryResult = NonNullable<Awaited<ReturnType<typeof getEnergyMix>>>
export type GetEnergyMixQueryError = AxiosError<unknown>


export function useGetEnergyMix<TData = Awaited<ReturnType<typeof getEnergyMix>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEnergyMix>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEnergyMix>>,
          TError,
          Awaited<ReturnType<typeof getEnergyMix>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEnergyMix<TData = Awaited<ReturnType<typeof getEnergyMix>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEnergyMix>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEnergyMix>>,
          TError,
          Awaited<ReturnType<typeof getEnergyMix>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEnergyMix<TData = Awaited<ReturnType<typeof getEnergyMix>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEnergyMix>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetEnergyMix<TData = Awaited<ReturnType<typeof getEnergyMix>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEnergyMix>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetEnergyMixQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




