/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CampaignBidResponse,
  CreateCampaignBidRequest
} from '../generated.schemas';





export const createCampaign = (
    createCampaignBidRequest: CreateCampaignBidRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CampaignBidResponse>> => {
    
    
    return axios.post(
      `http://localhost:8080/campaign-bids`,
      createCampaignBidRequest,options
    );
  }



export const getCreateCampaignMutationOptions = <TError = AxiosError<string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCampaign>>, TError,{data: CreateCampaignBidRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createCampaign>>, TError,{data: CreateCampaignBidRequest}, TContext> => {

const mutationKey = ['createCampaign'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCampaign>>, {data: CreateCampaignBidRequest}> = (props) => {
          const {data} = props ?? {};

          return  createCampaign(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCampaignMutationResult = NonNullable<Awaited<ReturnType<typeof createCampaign>>>
    export type CreateCampaignMutationBody = CreateCampaignBidRequest
    export type CreateCampaignMutationError = AxiosError<string>

    export const useCreateCampaign = <TError = AxiosError<string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCampaign>>, TError,{data: CreateCampaignBidRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCampaign>>,
        TError,
        {data: CreateCampaignBidRequest},
        TContext
      > => {

      const mutationOptions = getCreateCampaignMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    