/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  KeywordResponse,
  SearchKeywordsParams
} from '../generated.schemas';





export const searchKeywords = (
    params: SearchKeywordsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<KeywordResponse[]>> => {
    
    
    return axios.get(
      `http://localhost:8080/keywords`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getSearchKeywordsQueryKey = (params?: SearchKeywordsParams,) => {
    return [
    `http://localhost:8080/keywords`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getSearchKeywordsQueryOptions = <TData = Awaited<ReturnType<typeof searchKeywords>>, TError = AxiosError<string>>(params: SearchKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchKeywords>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchKeywordsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchKeywords>>> = ({ signal }) => searchKeywords(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchKeywords>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchKeywordsQueryResult = NonNullable<Awaited<ReturnType<typeof searchKeywords>>>
export type SearchKeywordsQueryError = AxiosError<string>


export function useSearchKeywords<TData = Awaited<ReturnType<typeof searchKeywords>>, TError = AxiosError<string>>(
 params: SearchKeywordsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchKeywords>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchKeywords>>,
          TError,
          Awaited<ReturnType<typeof searchKeywords>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchKeywords<TData = Awaited<ReturnType<typeof searchKeywords>>, TError = AxiosError<string>>(
 params: SearchKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchKeywords>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchKeywords>>,
          TError,
          Awaited<ReturnType<typeof searchKeywords>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchKeywords<TData = Awaited<ReturnType<typeof searchKeywords>>, TError = AxiosError<string>>(
 params: SearchKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchKeywords>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSearchKeywords<TData = Awaited<ReturnType<typeof searchKeywords>>, TError = AxiosError<string>>(
 params: SearchKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchKeywords>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchKeywordsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




