/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface CreateProductRequest {
  /** @minLength 1 */
  name: string;
  price: number;
}

export interface ProductResponse {
  name?: string;
  price?: number;
}

export interface CreateCampaignRequest {
  productId: string;
  /** @minLength 1 */
  name: string;
  minBidAmount: number;
  startsAt?: string;
  endsAt?: string;
}

export interface CampaignResponse {
  id?: string;
  name?: string;
  productId?: string;
  productName?: string;
  minBidAmount?: number;
  startsAt?: string;
  endsAt?: string;
}

export interface CreateCampaignBidRequest {
  /** @minLength 1 */
  name: string;
  keywords: string[];
  fund?: number;
}

export interface CampaignBidResponse {
  id?: string;
  name?: string;
  keywords?: string[];
  fund?: number;
}

export interface RegisterRequest {
  /**
   * @minLength 4
   * @maxLength 50
   */
  username: string;
  /**
   * @minLength 8
   * @maxLength 2147483647
   */
  password: string;
}

export interface UserResponse {
  id?: string;
  username?: string;
  balance?: number;
}

export interface LoginRequest {
  /** @minLength 1 */
  username: string;
  /** @minLength 1 */
  password: string;
}

export interface LoginResponse {
  token?: string;
}

export interface UpdateProductRequest {
  /** @minLength 1 */
  name: string;
  price: number;
}

export interface UpdateCampaignRequest {
  /** @minLength 1 */
  name: string;
  minBidAmount?: number;
  startsAt?: string;
  endsAt?: string;
}

export interface KeywordResponse {
  id?: number;
  keyword?: string;
}

export type GetKeywordsParams = {
/**
 * @minLength 1
 */
query: string;
};

export const getProducts = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProductResponse[]>> => {
    
    
    return axios.get(
      `http://localhost:8080/products`,options
    );
  }




export const getGetProductsQueryKey = () => {
    return [
    `http://localhost:8080/products`
    ] as const;
    }

    
export const getGetProductsQueryOptions = <TData = Awaited<ReturnType<typeof getProducts>>, TError = AxiosError<string | string | string>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProductsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProducts>>> = ({ signal }) => getProducts({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProductsQueryResult = NonNullable<Awaited<ReturnType<typeof getProducts>>>
export type GetProductsQueryError = AxiosError<string | string | string>


export function useGetProducts<TData = Awaited<ReturnType<typeof getProducts>>, TError = AxiosError<string | string | string>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProducts>>,
          TError,
          Awaited<ReturnType<typeof getProducts>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProducts<TData = Awaited<ReturnType<typeof getProducts>>, TError = AxiosError<string | string | string>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProducts>>,
          TError,
          Awaited<ReturnType<typeof getProducts>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProducts<TData = Awaited<ReturnType<typeof getProducts>>, TError = AxiosError<string | string | string>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetProducts<TData = Awaited<ReturnType<typeof getProducts>>, TError = AxiosError<string | string | string>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProducts>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProductsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const addProduct = (
    createProductRequest: CreateProductRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProductResponse>> => {
    
    
    return axios.post(
      `http://localhost:8080/products`,
      createProductRequest,options
    );
  }



export const getAddProductMutationOptions = <TError = AxiosError<string | string | string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addProduct>>, TError,{data: CreateProductRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof addProduct>>, TError,{data: CreateProductRequest}, TContext> => {

const mutationKey = ['addProduct'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addProduct>>, {data: CreateProductRequest}> = (props) => {
          const {data} = props ?? {};

          return  addProduct(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddProductMutationResult = NonNullable<Awaited<ReturnType<typeof addProduct>>>
    export type AddProductMutationBody = CreateProductRequest
    export type AddProductMutationError = AxiosError<string | string | string>

    export const useAddProduct = <TError = AxiosError<string | string | string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addProduct>>, TError,{data: CreateProductRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addProduct>>,
        TError,
        {data: CreateProductRequest},
        TContext
      > => {

      const mutationOptions = getAddProductMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getCampaigns = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CampaignResponse[]>> => {
    
    
    return axios.get(
      `http://localhost:8080/campaigns`,options
    );
  }




export const getGetCampaignsQueryKey = () => {
    return [
    `http://localhost:8080/campaigns`
    ] as const;
    }

    
export const getGetCampaignsQueryOptions = <TData = Awaited<ReturnType<typeof getCampaigns>>, TError = AxiosError<string | string | string>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCampaigns>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCampaignsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCampaigns>>> = ({ signal }) => getCampaigns({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCampaigns>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCampaignsQueryResult = NonNullable<Awaited<ReturnType<typeof getCampaigns>>>
export type GetCampaignsQueryError = AxiosError<string | string | string>


export function useGetCampaigns<TData = Awaited<ReturnType<typeof getCampaigns>>, TError = AxiosError<string | string | string>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCampaigns>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCampaigns>>,
          TError,
          Awaited<ReturnType<typeof getCampaigns>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCampaigns<TData = Awaited<ReturnType<typeof getCampaigns>>, TError = AxiosError<string | string | string>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCampaigns>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCampaigns>>,
          TError,
          Awaited<ReturnType<typeof getCampaigns>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCampaigns<TData = Awaited<ReturnType<typeof getCampaigns>>, TError = AxiosError<string | string | string>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCampaigns>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetCampaigns<TData = Awaited<ReturnType<typeof getCampaigns>>, TError = AxiosError<string | string | string>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCampaigns>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCampaignsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const createCampaign = (
    createCampaignRequest: CreateCampaignRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CampaignResponse>> => {
    
    
    return axios.post(
      `http://localhost:8080/campaigns`,
      createCampaignRequest,options
    );
  }



export const getCreateCampaignMutationOptions = <TError = AxiosError<string | string | string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCampaign>>, TError,{data: CreateCampaignRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createCampaign>>, TError,{data: CreateCampaignRequest}, TContext> => {

const mutationKey = ['createCampaign'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCampaign>>, {data: CreateCampaignRequest}> = (props) => {
          const {data} = props ?? {};

          return  createCampaign(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCampaignMutationResult = NonNullable<Awaited<ReturnType<typeof createCampaign>>>
    export type CreateCampaignMutationBody = CreateCampaignRequest
    export type CreateCampaignMutationError = AxiosError<string | string | string>

    export const useCreateCampaign = <TError = AxiosError<string | string | string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCampaign>>, TError,{data: CreateCampaignRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCampaign>>,
        TError,
        {data: CreateCampaignRequest},
        TContext
      > => {

      const mutationOptions = getCreateCampaignMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const createCampaignBid = (
    createCampaignBidRequest: CreateCampaignBidRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CampaignBidResponse>> => {
    
    
    return axios.post(
      `http://localhost:8080/campaign-bids`,
      createCampaignBidRequest,options
    );
  }



export const getCreateCampaignBidMutationOptions = <TError = AxiosError<string | string | string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCampaignBid>>, TError,{data: CreateCampaignBidRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createCampaignBid>>, TError,{data: CreateCampaignBidRequest}, TContext> => {

const mutationKey = ['createCampaignBid'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCampaignBid>>, {data: CreateCampaignBidRequest}> = (props) => {
          const {data} = props ?? {};

          return  createCampaignBid(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateCampaignBidMutationResult = NonNullable<Awaited<ReturnType<typeof createCampaignBid>>>
    export type CreateCampaignBidMutationBody = CreateCampaignBidRequest
    export type CreateCampaignBidMutationError = AxiosError<string | string | string>

    export const useCreateCampaignBid = <TError = AxiosError<string | string | string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCampaignBid>>, TError,{data: CreateCampaignBidRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCampaignBid>>,
        TError,
        {data: CreateCampaignBidRequest},
        TContext
      > => {

      const mutationOptions = getCreateCampaignBidMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const register = (
    registerRequest: RegisterRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserResponse>> => {
    
    
    return axios.post(
      `http://localhost:8080/auth/register`,
      registerRequest,options
    );
  }



export const getRegisterMutationOptions = <TError = AxiosError<string | string | string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: RegisterRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: RegisterRequest}, TContext> => {

const mutationKey = ['register'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof register>>, {data: RegisterRequest}> = (props) => {
          const {data} = props ?? {};

          return  register(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterMutationResult = NonNullable<Awaited<ReturnType<typeof register>>>
    export type RegisterMutationBody = RegisterRequest
    export type RegisterMutationError = AxiosError<string | string | string>

    export const useRegister = <TError = AxiosError<string | string | string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: RegisterRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof register>>,
        TError,
        {data: RegisterRequest},
        TContext
      > => {

      const mutationOptions = getRegisterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const login = (
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<LoginResponse>> => {
    
    
    return axios.post(
      `http://localhost:8080/auth/login`,
      loginRequest,options
    );
  }



export const getLoginMutationOptions = <TError = AxiosError<string | string | string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['login'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  login(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = LoginRequest
    export type LoginMutationError = AxiosError<string | string | string>

    export const useLogin = <TError = AxiosError<string | string | string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: LoginRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {

      const mutationOptions = getLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getProduct = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProductResponse>> => {
    
    
    return axios.get(
      `http://localhost:8080/products/${id}`,options
    );
  }




export const getGetProductQueryKey = (id?: string,) => {
    return [
    `http://localhost:8080/products/${id}`
    ] as const;
    }

    
export const getGetProductQueryOptions = <TData = Awaited<ReturnType<typeof getProduct>>, TError = AxiosError<string | string | string>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProduct>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProductQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProduct>>> = ({ signal }) => getProduct(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProduct>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProductQueryResult = NonNullable<Awaited<ReturnType<typeof getProduct>>>
export type GetProductQueryError = AxiosError<string | string | string>


export function useGetProduct<TData = Awaited<ReturnType<typeof getProduct>>, TError = AxiosError<string | string | string>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProduct>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProduct>>,
          TError,
          Awaited<ReturnType<typeof getProduct>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProduct<TData = Awaited<ReturnType<typeof getProduct>>, TError = AxiosError<string | string | string>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProduct>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProduct>>,
          TError,
          Awaited<ReturnType<typeof getProduct>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProduct<TData = Awaited<ReturnType<typeof getProduct>>, TError = AxiosError<string | string | string>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProduct>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetProduct<TData = Awaited<ReturnType<typeof getProduct>>, TError = AxiosError<string | string | string>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProduct>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProductQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const deleteProduct = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.delete(
      `http://localhost:8080/products/${id}`,options
    );
  }



export const getDeleteProductMutationOptions = <TError = AxiosError<string | string | string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProduct>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteProduct>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteProduct'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProduct>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteProduct(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteProductMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProduct>>>
    
    export type DeleteProductMutationError = AxiosError<string | string | string>

    export const useDeleteProduct = <TError = AxiosError<string | string | string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProduct>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProduct>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteProductMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const updateProduct = (
    id: string,
    updateProductRequest: UpdateProductRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProductResponse>> => {
    
    
    return axios.patch(
      `http://localhost:8080/products/${id}`,
      updateProductRequest,options
    );
  }



export const getUpdateProductMutationOptions = <TError = AxiosError<string | string | string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProduct>>, TError,{id: string;data: UpdateProductRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateProduct>>, TError,{id: string;data: UpdateProductRequest}, TContext> => {

const mutationKey = ['updateProduct'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProduct>>, {id: string;data: UpdateProductRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateProduct(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateProductMutationResult = NonNullable<Awaited<ReturnType<typeof updateProduct>>>
    export type UpdateProductMutationBody = UpdateProductRequest
    export type UpdateProductMutationError = AxiosError<string | string | string>

    export const useUpdateProduct = <TError = AxiosError<string | string | string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProduct>>, TError,{id: string;data: UpdateProductRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProduct>>,
        TError,
        {id: string;data: UpdateProductRequest},
        TContext
      > => {

      const mutationOptions = getUpdateProductMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getCampaign = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CampaignResponse>> => {
    
    
    return axios.get(
      `http://localhost:8080/campaigns/${id}`,options
    );
  }




export const getGetCampaignQueryKey = (id?: string,) => {
    return [
    `http://localhost:8080/campaigns/${id}`
    ] as const;
    }

    
export const getGetCampaignQueryOptions = <TData = Awaited<ReturnType<typeof getCampaign>>, TError = AxiosError<string | string | string>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCampaign>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCampaignQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCampaign>>> = ({ signal }) => getCampaign(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCampaign>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCampaignQueryResult = NonNullable<Awaited<ReturnType<typeof getCampaign>>>
export type GetCampaignQueryError = AxiosError<string | string | string>


export function useGetCampaign<TData = Awaited<ReturnType<typeof getCampaign>>, TError = AxiosError<string | string | string>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCampaign>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCampaign>>,
          TError,
          Awaited<ReturnType<typeof getCampaign>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCampaign<TData = Awaited<ReturnType<typeof getCampaign>>, TError = AxiosError<string | string | string>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCampaign>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCampaign>>,
          TError,
          Awaited<ReturnType<typeof getCampaign>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCampaign<TData = Awaited<ReturnType<typeof getCampaign>>, TError = AxiosError<string | string | string>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCampaign>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetCampaign<TData = Awaited<ReturnType<typeof getCampaign>>, TError = AxiosError<string | string | string>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCampaign>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCampaignQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const deleteCampaign = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.delete(
      `http://localhost:8080/campaigns/${id}`,options
    );
  }



export const getDeleteCampaignMutationOptions = <TError = AxiosError<string | string | string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCampaign>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCampaign>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteCampaign'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCampaign>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteCampaign(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCampaignMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCampaign>>>
    
    export type DeleteCampaignMutationError = AxiosError<string | string | string>

    export const useDeleteCampaign = <TError = AxiosError<string | string | string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCampaign>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCampaign>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteCampaignMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const updateCampaign = (
    id: string,
    updateCampaignRequest: UpdateCampaignRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CampaignResponse>> => {
    
    
    return axios.patch(
      `http://localhost:8080/campaigns/${id}`,
      updateCampaignRequest,options
    );
  }



export const getUpdateCampaignMutationOptions = <TError = AxiosError<string | string | string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCampaign>>, TError,{id: string;data: UpdateCampaignRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateCampaign>>, TError,{id: string;data: UpdateCampaignRequest}, TContext> => {

const mutationKey = ['updateCampaign'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCampaign>>, {id: string;data: UpdateCampaignRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateCampaign(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateCampaignMutationResult = NonNullable<Awaited<ReturnType<typeof updateCampaign>>>
    export type UpdateCampaignMutationBody = UpdateCampaignRequest
    export type UpdateCampaignMutationError = AxiosError<string | string | string>

    export const useUpdateCampaign = <TError = AxiosError<string | string | string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCampaign>>, TError,{id: string;data: UpdateCampaignRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateCampaign>>,
        TError,
        {id: string;data: UpdateCampaignRequest},
        TContext
      > => {

      const mutationOptions = getUpdateCampaignMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getUser = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserResponse>> => {
    
    
    return axios.get(
      `http://localhost:8080/users/me`,options
    );
  }




export const getGetUserQueryKey = () => {
    return [
    `http://localhost:8080/users/me`
    ] as const;
    }

    
export const getGetUserQueryOptions = <TData = Awaited<ReturnType<typeof getUser>>, TError = AxiosError<string | string | string>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUser>>> = ({ signal }) => getUser({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserQueryResult = NonNullable<Awaited<ReturnType<typeof getUser>>>
export type GetUserQueryError = AxiosError<string | string | string>


export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = AxiosError<string | string | string>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUser>>,
          TError,
          Awaited<ReturnType<typeof getUser>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = AxiosError<string | string | string>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUser>>,
          TError,
          Awaited<ReturnType<typeof getUser>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = AxiosError<string | string | string>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = AxiosError<string | string | string>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getKeywords = (
    params: GetKeywordsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<KeywordResponse[]>> => {
    
    
    return axios.get(
      `http://localhost:8080/keywords`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetKeywordsQueryKey = (params?: GetKeywordsParams,) => {
    return [
    `http://localhost:8080/keywords`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetKeywordsQueryOptions = <TData = Awaited<ReturnType<typeof getKeywords>>, TError = AxiosError<string | string | string>>(params: GetKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getKeywords>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetKeywordsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getKeywords>>> = ({ signal }) => getKeywords(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getKeywords>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetKeywordsQueryResult = NonNullable<Awaited<ReturnType<typeof getKeywords>>>
export type GetKeywordsQueryError = AxiosError<string | string | string>


export function useGetKeywords<TData = Awaited<ReturnType<typeof getKeywords>>, TError = AxiosError<string | string | string>>(
 params: GetKeywordsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getKeywords>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getKeywords>>,
          TError,
          Awaited<ReturnType<typeof getKeywords>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetKeywords<TData = Awaited<ReturnType<typeof getKeywords>>, TError = AxiosError<string | string | string>>(
 params: GetKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getKeywords>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getKeywords>>,
          TError,
          Awaited<ReturnType<typeof getKeywords>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetKeywords<TData = Awaited<ReturnType<typeof getKeywords>>, TError = AxiosError<string | string | string>>(
 params: GetKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getKeywords>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetKeywords<TData = Awaited<ReturnType<typeof getKeywords>>, TError = AxiosError<string | string | string>>(
 params: GetKeywordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getKeywords>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetKeywordsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}
