/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
export interface CreateProductRequest {
  /** @minLength 1 */
  name: string;
  price: number;
}

export interface ProductResponse {
  name?: string;
  price?: number;
}

export interface CreateCampaignRequest {
  productId: string;
  /** @minLength 1 */
  name: string;
  minBidAmount: number;
  startsAt?: string;
  endsAt?: string;
}

export interface CampaignResponse {
  id?: string;
  name?: string;
  productId?: string;
  productName?: string;
  minBidAmount?: number;
  startsAt?: string;
  endsAt?: string;
}

export interface CreateCampaignBidRequest {
  /** @minLength 1 */
  name: string;
  keywords: string[];
  fund?: number;
}

export interface CampaignBidResponse {
  id?: string;
  name?: string;
  keywords?: string[];
  fund?: number;
}

export interface RegisterRequest {
  /**
   * @minLength 4
   * @maxLength 50
   */
  username: string;
  /**
   * @minLength 8
   * @maxLength 2147483647
   */
  password: string;
}

export interface UserResponse {
  id?: string;
  username?: string;
  balance?: number;
}

export interface LoginRequest {
  /** @minLength 1 */
  username: string;
  /** @minLength 1 */
  password: string;
}

export interface LoginResponse {
  token?: string;
}

export interface UpdateProductRequest {
  /** @minLength 1 */
  name: string;
  price: number;
}

export interface UpdateCampaignRequest {
  /** @minLength 1 */
  name: string;
  minBidAmount?: number;
  startsAt?: string;
  endsAt?: string;
}

export interface KeywordResponse {
  id?: number;
  keyword?: string;
}

export type GetKeywordsParams = {
/**
 * @minLength 1
 */
query: string;
};

